// Import the generated Prisma Client.
//Prisma client -> Js interface to the PostgreSQL database. It is generated by Prisma based on the schema.prisma file.
const { PrismaClient } = require("@prisma/client");

// Enable SQL query logging during local development.
// Avoid detailed query logs in test and production environments.
let options;

if (!process.env.NODE_ENV || process.env.NODE_ENV === "development") {
  options = {
    log: ["query"],
  };
} else {
  options = {};
}

// Create one shared Prisma Client instance for the application.
// Reusing one instance prevents unnecessary database connection pools.
const prisma = new PrismaClient(options);

// Export the shared client for controllers and app.js.
module.exports = prisma;